(playbook "kubespray/roles/container-engine/docker/vars/fedora.yml"
  (containerd_versioned_pkg 
    (latest (jinja "{{ containerd_package }}"))
    (1.3.7 (jinja "{{ containerd_package }}") "-1.3.7-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.3.9 (jinja "{{ containerd_package }}") "-1.3.9-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.4.3 (jinja "{{ containerd_package }}") "-1.4.3-3.2.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.4.4 (jinja "{{ containerd_package }}") "-1.4.4-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.4.6 (jinja "{{ containerd_package }}") "-1.4.6-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.4.9 (jinja "{{ containerd_package }}") "-1.4.9-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.4.12 (jinja "{{ containerd_package }}") "-1.4.12-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.4 (jinja "{{ containerd_package }}") "-1.6.4-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.6 (jinja "{{ containerd_package }}") "-1.6.6-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.7 (jinja "{{ containerd_package }}") "-1.6.7-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.8 (jinja "{{ containerd_package }}") "-1.6.8-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.9 (jinja "{{ containerd_package }}") "-1.6.9-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.10 (jinja "{{ containerd_package }}") "-1.6.10-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.11 (jinja "{{ containerd_package }}") "-1.6.11-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.12 (jinja "{{ containerd_package }}") "-1.6.12-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.13 (jinja "{{ containerd_package }}") "-1.6.13-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.14 (jinja "{{ containerd_package }}") "-1.6.14-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.15 (jinja "{{ containerd_package }}") "-1.6.15-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.16 (jinja "{{ containerd_package }}") "-1.6.16-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.18 (jinja "{{ containerd_package }}") "-1.6.18-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.28 (jinja "{{ containerd_package }}") "-1.6.28-3.2.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.31 (jinja "{{ containerd_package }}") "-1.6.31-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.32 (jinja "{{ containerd_package }}") "-1.6.32-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.6.33 (jinja "{{ containerd_package }}") "-1.6.33-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.7.18 (jinja "{{ containerd_package }}") "-1.7.18-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.7.19 (jinja "{{ containerd_package }}") "-1.7.19-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.7.20 (jinja "{{ containerd_package }}") "-1.7.20-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.7.21 (jinja "{{ containerd_package }}") "-1.7.21-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.7.22 (jinja "{{ containerd_package }}") "-1.7.22-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.7.23 (jinja "{{ containerd_package }}") "-1.7.23-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.7.24 (jinja "{{ containerd_package }}") "-1.7.24-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.7.25 (jinja "{{ containerd_package }}") "-1.7.25-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.7.26 (jinja "{{ containerd_package }}") "-1.7.26-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (1.7.27 (jinja "{{ containerd_package }}") "-1.7.27-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (stable (jinja "{{ containerd_package }}") "-1.7.27-3.1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (edge (jinja "{{ containerd_package }}") "-1.7.27-3.1.fc" (jinja "{{ ansible_distribution_major_version }}")))
  (docker_versioned_pkg 
    (latest "docker-ce")
    (19.03 "docker-ce-19.03.15-3.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (20.10 "docker-ce-20.10.20-3.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (23.0 "docker-ce-3:23.0.6-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (24.0 "docker-ce-3:24.0.9-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (26.0 "docker-ce-3:26.0.2-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (26.1 "docker-ce-3:26.1.4-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (27.0 "docker-ce-3:27.0.3-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (27.1 "docker-ce-3:27.1.2-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (27.2 "docker-ce-3:27.2.1-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (27.3 "docker-ce-3:27.3.1-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (27.4 "docker-ce-3:27.4.1-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (27.5 "docker-ce-3:27.5.1-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (28.0 "docker-ce-3:28.0.4-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (28.1 "docker-ce-3:28.1.1-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (28.2 "docker-ce-3:28.2.2-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (28.3 "docker-ce-3:28.3.3-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (stable "docker-ce-3:28.3.3-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (edge "docker-ce-3:28.3.3-1.fc" (jinja "{{ ansible_distribution_major_version }}")))
  (docker_cli_versioned_pkg 
    (latest "docker-ce-cli")
    (19.03 "docker-ce-cli-19.03.15-3.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (20.10 "docker-ce-cli-20.10.20-3.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (23.0 "docker-ce-cli-1:23.0.6-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (24.0 "docker-ce-cli-1:24.0.9-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (26.0 "docker-ce-cli-1:26.0.2-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (26.1 "docker-ce-cli-1:26.1.4-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (27.0 "docker-ce-cli-1:27.0.3-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (27.1 "docker-ce-cli-1:27.1.2-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (27.2 "docker-ce-cli-1:27.2.1-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (27.3 "docker-ce-cli-1:27.3.1-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (27.4 "docker-ce-cli-1:27.4.1-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (27.5 "docker-ce-cli-1:27.5.1-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (28.0 "docker-ce-cli-1:28.0.4-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (28.1 "docker-ce-cli-1:28.1.1-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (28.2 "docker-ce-cli-1:28.2.2-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (28.3 "docker-ce-cli-1:28.3.3-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (stable "docker-ce-cli-1:28.3.3-1.fc" (jinja "{{ ansible_distribution_major_version }}"))
    (edge "docker-ce-cli-1:28.3.3-1.fc" (jinja "{{ ansible_distribution_major_version }}")))
  (docker_package_info 
    (enablerepo "docker-ce")
    (pkgs (list
        (jinja "{{ containerd_versioned_pkg[docker_containerd_version | string] }}")
        (jinja "{{ docker_cli_versioned_pkg[docker_cli_version | string] }}")
        (jinja "{{ docker_versioned_pkg[docker_version | string] }}")))))
