(playbook "kubespray/roles/kubernetes/control-plane/defaults/main/main.yml"
  (upgrade_cluster_setup "false")
  (control_plane_node_become_ready_tries "24")
  (kube_apiserver_bind_address "::")
  (kube_apiserver_node_port_range "30000-32767")
  (kube_apiserver_storage_backend "etcd3")
  (kube_apiserver_etcd_compaction_interval "5m0s")
  (kube_apiserver_service_account_lookup "true")
  (kube_etcd_cacert_file "ca.pem")
  (kube_etcd_cert_file "node-" (jinja "{{ inventory_hostname }}") ".pem")
  (kube_etcd_key_file "node-" (jinja "{{ inventory_hostname }}") "-key.pem")
  (kube_controller_manager_bind_address "::")
  (control_plane_health_retries "60")
  (kube_controller_manager_leader_elect_lease_duration "15s")
  (kube_controller_manager_leader_elect_renew_deadline "10s")
  (discovery_timeout "5m0s")
  (kubeadm_refresh_token "true")
  (kubeadm_scale_down_coredns_enabled "true")
  (kubernetes_audit "false")
  (audit_log_path "/var/log/audit/kube-apiserver-audit.log")
  (audit_log_maxage "30")
  (audit_log_maxbackups "10")
  (audit_log_maxsize "100")
  (audit_policy_file (jinja "{{ kube_config_dir }}") "/audit-policy/apiserver-audit-policy.yaml")
  (audit_log_name "audit-logs")
  (audit_log_hostpath "/var/log/kubernetes/audit")
  (audit_log_mountpath (jinja "{{ audit_log_path | dirname }}"))
  (audit_policy_name "audit-policy")
  (audit_policy_hostpath (jinja "{{ audit_policy_file | dirname }}"))
  (audit_policy_mountpath (jinja "{{ audit_policy_hostpath }}"))
  (kubernetes_audit_webhook "false")
  (audit_webhook_config_file (jinja "{{ kube_config_dir }}") "/audit-policy/apiserver-audit-webhook-config.yaml")
  (audit_webhook_server_url "https://audit.app")
  (audit_webhook_server_extra_args )
  (audit_webhook_mode "batch")
  (audit_webhook_batch_max_size "100")
  (audit_webhook_batch_max_wait "1s")
  (kube_controller_node_monitor_grace_period "40s")
  (kube_controller_node_monitor_period "5s")
  (kube_controller_terminated_pod_gc_threshold "12500")
  (kube_apiserver_request_timeout "1m0s")
  (kube_apiserver_pod_eviction_not_ready_timeout_seconds "300")
  (kube_apiserver_pod_eviction_unreachable_timeout_seconds "300")
  (kube_apiserver_enable_admission_plugins (list))
  (kube_apiserver_admission_control_config_file "false")
  (kube_apiserver_admission_event_rate_limits )
  (kube_pod_security_use_default "false")
  (kube_pod_security_default_enforce "baseline")
  (kube_pod_security_default_enforce_version "v" (jinja "{{ kube_major_version }}"))
  (kube_pod_security_default_audit "restricted")
  (kube_pod_security_default_audit_version "v" (jinja "{{ kube_major_version }}"))
  (kube_pod_security_default_warn "restricted")
  (kube_pod_security_default_warn_version "v" (jinja "{{ kube_major_version }}"))
  (kube_pod_security_exemptions_usernames (list))
  (kube_pod_security_exemptions_runtime_class_names (list))
  (kube_pod_security_exemptions_namespaces (list
      "kube-system"))
  (kube_resource_quota_limited_resources (list))
  (kube_apiserver_disable_admission_plugins (list))
  (kube_api_runtime_config (list))
  (kube_token_auth "false")
  (kube_oidc_auth "false")
  (kube_webhook_token_auth "false")
  (kube_webhook_token_auth_url_skip_tls_verify "false")
  (kube_webhook_authorization "false")
  (kube_webhook_authorization_url_skip_tls_verify "false")
  (kube_apiserver_admission_plugins_podnodeselector_default_node_selector "")
  (kubelet_preferred_address_types "InternalDNS,InternalIP,Hostname,ExternalDNS,ExternalIP")
  (kube_kubeadm_apiserver_extra_args )
  (kube_kubeadm_controller_extra_args )
  (apiserver_extra_volumes )
  (controller_manager_extra_volumes )
  (kube_encrypt_secret_data "false")
  (kube_encrypt_token (jinja "{{ lookup('password', credentials_dir + '/kube_encrypt_token.creds length=32 chars=ascii_letters,digits') }}"))
  (kube_encryption_algorithm "secretbox")
  (kube_encryption_resources (list
      "secrets"))
  (secrets_encryption_query "resources[*].providers[0]." (jinja "{{ kube_encryption_algorithm }}") ".keys[0].secret")
  (event_ttl_duration "1h0m0s")
  (auto_renew_certificates "false")
  (auto_renew_certificates_systemd_calendar "Mon *-*-1,2,3,4,5,6,7 03:00:00")
  (kubeadm_upgrade_auto_cert_renewal "true")
  (supplementary_addresses_in_ssl_keys (list))
  (kube_apiserver_tracing "false")
  (kube_apiserver_tracing_endpoint "[::]:4317")
  (kube_apiserver_tracing_sampling_rate_per_million "100")
  (kubeadm_use_file_discovery (jinja "{{ remove_anonymous_access }}"))
  (kubeadm_image_pull_serial "true")
  (kube_asymmetric_encryption_algorithm "RSA-2048")
  (kube_cert_validity_period "8760h")
  (kube_ca_cert_validity_period "87600h"))
