(playbook "kubespray/roles/kubernetes-apps/external_cloud_controller/openstack/defaults/main.yml"
  (external_openstack_auth_url (jinja "{{ lookup('env', 'OS_AUTH_URL') }}"))
  (external_openstack_username (jinja "{{ lookup('env', 'OS_USERNAME') }}"))
  (external_openstack_password (jinja "{{ lookup('env', 'OS_PASSWORD') }}"))
  (external_openstack_application_credential_id (jinja "{{ lookup('env', 'OS_APPLICATION_CREDENTIAL_ID') }}"))
  (external_openstack_application_credential_name (jinja "{{ lookup('env', 'OS_APPLICATION_CREDENTIAL_NAME') }}"))
  (external_openstack_application_credential_secret (jinja "{{ lookup('env', 'OS_APPLICATION_CREDENTIAL_SECRET') }}"))
  (external_openstack_region (jinja "{{ lookup('env', 'OS_REGION_NAME') }}"))
  (external_openstack_tenant_id (jinja "{{ lookup('env', 'OS_TENANT_ID') | default(lookup('env', 'OS_PROJECT_ID'), true) }}"))
  (external_openstack_tenant_name (jinja "{{ lookup('env', 'OS_TENANT_NAME') | default(lookup('env', 'OS_PROJECT_NAME'), true) }}"))
  (external_openstack_domain_name (jinja "{{ lookup('env', 'OS_USER_DOMAIN_NAME') }}"))
  (external_openstack_domain_id (jinja "{{ lookup('env', 'OS_USER_DOMAIN_ID') }}"))
  (external_openstack_cacert (jinja "{{ lookup('env', 'OS_CACERT') }}"))
  (external_openstack_cloud_controller_extra_args )
  (external_openstack_cloud_controller_image_tag "v1.35.0")
  (external_openstack_cloud_controller_bind_address "127.0.0.1")
  (external_openstack_cloud_controller_dns_policy "ClusterFirst")
  (external_openstack_lbaas_member_subnet_id (jinja "{{ external_openstack_lbaas_subnet_id }}")))
